apiVersion: v2
name: teslamate
description: A Helm chart for TeslaMate - self-hosted data logger for Tesla vehicles
type: application
version: 0.1.0
appVersion: "2.2.0"
keywords:
  - teslamate
  - tesla
  - grafana
  - postgres
  - mqtt
home: https://docs.teslamate.org
sources:
  - https://github.com/teslamate-org/teslamate
maintainers: []
license: MIT
