{{- if .Values.mosquitto.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "teslamate.mosquitto.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "teslamate.mosquittoPort" . }}
      targetPort: 1883
      protocol: TCP
      name: mqtt
  selector:
    {{- include "teslamate.mosquitto.selectorLabels" . | nindent 4 }}
{{- end }}
